zurg: v1
token: ''
strm_link_token: ''
api_rate_limit_per_minute: 250
api_timeout_secs: 60
auto_analyze_new_torrents: false
base_url: ''
cache_network_test_results: false
enable_repair: false
delete_error_torrents: false
delete_torrent_if_extensions_found: []
do_not_use_cdn_hosts: false
downloads_every_mins: 720
get_downloads_limit: 0
download_timeout_secs: 15
download_tokens: []
emby_server_url: ''
emby_token: ''
fetch_torrents_page_size: 5000
force_ipv6: false
force_select_playable_files: false
hide_broken_torrents: false
host: '[::]'
ignore_renames: false
jellyfin_server_url: ''
jellyfin_token: ''
load_dumped_torrents: false
log_requests: false
mount_path: ''
number_of_hosts: 0
on_library_update: ''
password: ''
addl_playable_extensions: []
plex_server_url: ''
plex_token: ''
plex_match_every_mins: 0
port: '9999'
proxy: ''
rar_action: none
restrict_repair_to_cached: false
check_for_changes_every_secs: 15
repair_every_mins: 60
repair_timeout_mins: 30
retain_folder_name_extension: false
retain_rd_torrent_name: false
retries_until_failed: 2
retry_503_errors: false
save_strm_files: false
disable_stream_proxy: false
serve_strm_files: false
torrents_rate_limit_per_minute: 75
unrestrict_ip: ''
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
username: ''
# Replace the values
